### ISSUE TITLE
Option to load examples in iframes

### ISSUE THREAD

**Issue by toddparker** [filamentgroup/X-rayHTML#13]
If your docs layout has things like a left nav, it messes with the media queries of a component. Can we add the option to load examples in an iframe to help with this? We'd need to define some sort of a template to pull the code into. Having these iframes be re-sizable by the user would be cool, but these at the very lest need to reflow with the layout

**Comment by toddparker** [comment]
@johnbender - check this out:
http://dev.edenspiekermann.com/2016/04/05/introducing-iframify/

**Comment by johnbender** [comment]
Merged
