### ISSUE TITLE
Trouble getting the release version to work

### ISSUE THREAD

**Issue by benbrowning** [filamentgroup/X-rayHTML#2]
I followed the instructions in your readme, using the download links at the start of the Getting started section and couldn't get it to work. After some investigation it looks like the config options in the downloadable version have the plugin name set to be 'view-source', but the instructions still suggest that data-xrayhtml should be used as the attribute, which just fails silently.
I've fixed this by using the latest version of the source code which has the correct default options, but thought you would like to know.

**Comment by zachleat** [comment]
I’ve adopted this repo and taken it under my wing—are you still having this issue? Please reopen if necessary.
