### ISSUE TITLE
iframe example malfunctioning

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/X-rayHTML#21]
https://github.com/filamentgroup/X-rayHTML/blame/master/index.html#L72

![image](https://cloud.githubusercontent.com/assets/39355/21360556/05a99dae-c6a6-11e6-91d8-66b9dcb90103.png)

**Comment by maggiewachs** [comment]
Taking a look at this one, will holler if I need help. :)

**Comment by maggiewachs** [comment]
@zachleat I'm not able to reproduce this. Is is happening in a specific browser?

**Comment by zachleat** [comment]
@maggiewachs I wasn’t able to reproduce it any more either. Must’ve been fixed!
