### ISSUE TITLE
Move stuff out of `libs` and into package.json as dependencies

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/X-rayHTML#28]
For easier maintenance, we want to move away from manual copies of the libs here:
![image](https://user-images.githubusercontent.com/39355/27706213-57e31818-5cd6-11e7-9cdd-81020a164e13.png)

Use `npm` to load and update these.

**Comment by maggiewachs** [comment]
Closed with 1cba48a5b4c50f880bb941ac2b28181823c38cdd
